version: "3.9"
services:
  slimer-database:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD:
      POSTGRES_HOST_AUTH_METHOD: trust
  slimer-redis:
    image: redis
    ports:
      - "6379"
    volumes:
      - slimer-redis:/data
  slimer:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec puma -C config/puma.rb"
    environment:
      REDIS_URL: "redis://slimer-redis:6379"
      DATABASE_URL: "postgres://slimer-database/?pool=8"
    volumes:
      - .:/slimer
    ports:
      - "6660:6660"
    depends_on:
      - slimer-database
      - slimer-redis
  slimer-workers:
    build: .
    command: bash -c "bundle exec sidekiq -C config/sidekiq.yml -r ./application.rb"
    environment:
      REDIS_URL: "redis://slimer-redis:6379"
      DATABASE_URL: "postgres://slimer-database/?pool=8"
    volumes:
      - .:/slimer
    depends_on:
      - slimer-database
      - slimer-redis

volumes:
  slimer-database:
  slimer-redis:
  slimer-tmp-cache:
